node {
   echo "hello"
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()      
      File file = new File("commit.txt")
     file.write("first")
   }  
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '337aa92f-7721-413b-acf2-9b7c2c3b4e19') {
       def app = docker.build("gourabbanerjee05/test007:${commit_id}", '.').push()
     }
   }
}
